language: python
sudo: required

#addons:
#  apt:
#    packages:
#    - gromacs

python:
  - "2.7"
  - "3.6"

before_install:
  - wget ftp://ftp.gromacs.org/pub/gromacs/gromacs-2016.5.tar.gz
  - tar xfz gromacs-2016.5.tar.gz
  - cd gromacs-2016.5
  - mkdir build
  - cd build
  - cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=OFF
  - make
  - make check
  - sudo make install
  - source /usr/local/gromacs/bin/GMXRC
  - gmx --version

# command to install dependencies and package
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - py.test --cov=paratemp
after_success:
  - coveralls
