language: python

python:
  - "2.7"
  - "3.6"

# command to install dependencies and package
install:
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - py.test # or py.test for Python versions 3.5 and below
