language: python
cache: pip

addons:
  apt:
    packages:
    - gromacs

python:
  - "3.5"
  - "3.6"
# Enable 3.7 without globally enabling sudo and dist: xenial for
# other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      addons:
        apt:
          packages:
            - gromacs
            - libhdf5-dev

# command to install dependencies and package
install:
  - pip install -e .[tests]

# command to run tests
script:
  - py.test --cov=paratemp

after_success:
  - coveralls

notifications:
  slack:
    secure: "ju/C2pgfqgoxMBtItRziF5gLnd31XvY/6+DcccX+l1y6Mn32hvkSDKBcupRbtrVbqq5/m5jPUu6Uz3WMP7mL129rLNuYfMEaXVLw3NR+TmDGiNPLBThJcfAdzVP1GOSTr97lG763f97ruzxfbvpxWa28/q/JEj3eIkqDrhRbqT49+Bj6dFB5T1MW6IGPiwTIEqa3+QNP4nh+YCPSUdE3bO+ks5C2wXn0NQmc5aEBs5RNhFTVHI2I37oe6RfZyFDc78KiHtDRzIs/b6yQOoa3LO17TxQoTvlXKOeBojcj2HX75Rjxs+gnKHy4UM3A16b85ba2KiUJ1ZJxMce22TN3tPD9+iur3Lk2ZEhlyxtgvRWfGMA++MSmlmI/+T6Z4rMbvXQpqqPzBMptkcaXha7hfla8XHD2jeiqiy8iqlIz7R9xXv8H5Pdb4r77LXaNESQehLbTFBo+pji0awiy3j/I0QsDykuU6FGB8168sq23KVX8yp0mZ4D/azU9S64e5VGiKtpntqJG3XlnFowMrVofQRjI7x4BFjshkRv6nBsfp5QYIa8+QLb+FrYS4KOF2qdhfoCHy6igwpHUlP8ZodF781sfmmm4opGHNEn8excBjwu6ZdQLbPNVMPQ3HvuUl2llpvIk1HkDS0DTJqlMnLwAggzP4n/pO1z0u01U9Yy6GHA="

